INSERT INTO [Bird] (CommonName, ScientificName) VALUES 
	('Black-bellied Whistling-Duck', 'Dendrocygna autumnalis'), 
	('Fulvous Whistling-Duck', 'Dendrocygna bicolor'), 
	('Snow Goose', 'Anser caerulescens'), 
	('Ross''s Goose', 'Anser rossii'), 
	('Greater White-fronted Goose', 'Anser albifrons'), 
	('Pink-footed Goose', 'Anser brachyrhynchus'), 
	('Brant', 'Branta bernicla'), 
	('Cackling Goose', 'Branta hutchinsii'), 
	('Canada Goose', 'Branta canadensis'), 
	('Mute Swan', 'Cygnus olor'), 
	('Trumpeter Swan', 'Cygnus buccinator'), 
	('Tundra Swan', 'Cygnus columbianus'), 
	('Wood Duck', 'Aix sponsa'), 
	('Garganey', 'Spatula querquedula'), 
	('Blue-winged Teal', 'Spatula discors'), 
	('Cinnamon Teal', 'Spatula cyanoptera'), 
	('Northern Shoveler', 'Spatula clypeata'), 
	('Gadwall', 'Mareca strepera'), 
	('Eurasian Wigeon', 'Mareca penelope'), 
	('American Wigeon', 'Mareca americana'), 
	('Mallard', 'Anas platyrhynchos'), 
	('American Black Duck', 'Anas rubripes'), 
	('Northern Pintail', 'Anas acuta'), 
	('Green-winged Teal', 'Anas crecca'), 
	('Canvasback', 'Aythya valisineria'), 
	('Redhead', 'Aythya americana'), 
	('Ring-necked Duck', 'Aythya collaris'), 
	('Tufted Duck', 'Aythya fuligula'), 
	('Greater Scaup', 'Aythya marila'), 
	('Lesser Scaup', 'Aythya affinis'), 
	('King Eider', 'Somateria spectabilis'), 
	('Common Eider', 'Somateria mollissima'), 
	('Harlequin Duck', 'Histrionicus histrionicus'), 
	('Surf Scoter', 'Melanitta perspicillata'), 
	('White-winged Scoter', 'Melanitta deglandi'), 
	('Black Scoter', 'Melanitta americana'), 
	('Long-tailed Duck', 'Clangula hyemalis'), 
	('Bufflehead', 'Bucephala albeola'), 
	('Common Goldeneye', 'Bucephala clangula'), 
	('Barrow''s Goldeneye', 'Bucephala islandica'), 
	('Hooded Merganser', 'Lophodytes cucullatus'), 
	('Common Merganser', 'Mergus merganser'), 
	('Red-breasted Merganser', 'Mergus serrator'), 
	('Ruddy Duck', 'Oxyura jamaicensis'), 
	('Northern Bobwhite', 'Colinus virginianus'), 
	('Wild Turkey', 'Meleagris gallopavo'), 
	('Ruffed Grouse', 'Bonasa umbellus'), 
	('Spruce Grouse', 'Falcipennis canadensis'), 
	('Sharp-tailed Grouse', 'Tympanuchus phasianellus'), 
	('Greater Prairie-Chicken', 'Tympanuchus cupido'), 
	('Ring-necked Pheasant', 'Phasianus colchicus'), 
	('Pied-billed Grebe', 'Podilymbus podiceps'), 
	('Horned Grebe', 'Podiceps auritus'), 
	('Red-necked Grebe', 'Podiceps grisegena'), 
	('Eared Grebe', 'Podiceps nigricollis'), 
	('Western Grebe', 'Aechmophorus occidentalis'), 
	('Rock Pigeon', 'Columba livia'), 
	('Band-tailed Pigeon', 'Patagioenas fasciata'), 
	('Eurasian Collared-Dove', 'Streptopelia decaocto'), 
	('Passenger Pigeon', 'Ectopistes migratorius'), 
	('Inca Dove', 'Columbina inca'), 
	('Common Ground Dove', 'Columbina passerina'), 
	('White-winged Dove', 'Zenaida asiatica'), 
	('Mourning Dove', 'Zenaida macroura'), 
	('Groove-billed Ani', 'Crotophaga sulcirostris'), 
	('Yellow-billed Cuckoo', 'Coccyzus americanus'), 
	('Black-billed Cuckoo', 'Coccyzus erythropthalmus'), 
	('Common Nighthawk', 'Chordeiles minor'), 
	('Chuck-will''s-widow', 'Antrostomus carolinensis'), 
	('Eastern Whip-poor-will', 'Antrostomus vociferus'), 
	('White-collared Swift', 'Streptoprocne zonaris'), 
	('Chimney Swift', 'Chaetura pelagica'), 
	('White-throated Swift', 'Aeronautes saxatalis'), 
	('Mexican Violetear', 'Colibri thalassinus'), 
	('Ruby-throated Hummingbird', 'Archilochus colubris'), 
	('Anna''s Hummingbird', 'Calypte anna'), 
	('Costa''s Hummingbird', 'Calypte costae'), 
	('Rufous Hummingbird', 'Selasphorus rufus'), 
	('Broad-billed Hummingbird', 'Cynanthus latirostris'), 
	('White-eared Hummingbird', 'Basilinna leucotis'), 
	('Berylline Hummingbird', 'Amazilia beryllina'), 
	('King Rail', 'Rallus elegans'), 
	('Virginia Rail', 'Rallus limicola'), 
	('Sora', 'Porzana carolina'), 
	('Black Rail', 'Laterallus jamaicensis'), 
	('Common Gallinule', 'Gallinula galeata'), 
	('American Coot', 'Fulica americana'), 
	('Purple Gallinule', 'Porphyrio martinicus'), 
	('Yellow Rail', 'Coturnicops noveboracensis'), 
	('Limpkin', 'Aramus guarauna'), 
	('Sandhill Crane', 'Antigone canadensis'), 
	('Black-necked Stilt', 'Himantopus mexicanus'), 
	('American Avocet', 'Recurvirostra americana'), 
	('Black-bellied Plover', 'Pluvialis squatarola'), 
	('American Golden-Plover', 'Pluvialis dominica'), 
	('Killdeer', 'Charadrius vociferus'), 
	('Semipalmated Plover', 'Charadrius semipalmatus'), 
	('Piping Plover', 'Charadrius melodus'), 
	('Wilson''s Plover', 'Charadrius wilsonia'), 
	('Snowy Plover', 'Charadrius nivosus'), 
	('Upland Sandpiper', 'Bartramia longicauda'), 
	('Whimbrel', 'Numenius phaeopus'), 
	('Eskimo Curlew', 'Numenius borealis'), 
	('Long-billed Curlew', 'Numenius americanus'), 
	('Bar-tailed Godwit', 'Limosa lapponica'), 
	('Hudsonian Godwit', 'Limosa haemastica'), 
	('Marbled Godwit', 'Limosa fedoa'), 
	('Ruddy Turnstone', 'Arenaria interpres'), 
	('Red Knot', 'Calidris canutus'), 
	('Ruff', 'Calidris pugnax'), 
	('Sharp-tailed Sandpiper', 'Calidris acuminata'), 
	('Stilt Sandpiper', 'Calidris himantopus'), 
	('Curlew Sandpiper', 'Calidris ferruginea'), 
	('Sanderling', 'Calidris alba'), 
	('Dunlin', 'Calidris alpina'), 
	('Purple Sandpiper', 'Calidris maritima'), 
	('Baird''s Sandpiper', 'Calidris bairdii'), 
	('Least Sandpiper', 'Calidris minutilla'), 
	('White-rumped Sandpiper', 'Calidris fuscicollis'), 
	('Buff-breasted Sandpiper', 'Calidris subruficollis'), 
	('Pectoral Sandpiper', 'Calidris melanotos'), 
	('Semipalmated Sandpiper', 'Calidris pusilla'), 
	('Western Sandpiper', 'Calidris mauri'), 
	('Short-billed Dowitcher', 'Limnodromus griseus'), 
	('Long-billed Dowitcher', 'Limnodromus scolopaceus'), 
	('American Woodcock', 'Scolopax minor'), 
	('Wilson''s Snipe', 'Gallinago delicata'), 
	('Spotted Sandpiper', 'Actitis macularius'), 
	('Solitary Sandpiper', 'Tringa solitaria'), 
	('Gray-tailed/Wandering Tattler', 'Tringa brevipes/incana'), 
	('Lesser Yellowlegs', 'Tringa flavipes'), 
	('Willet', 'Tringa semipalmata'), 
	('Spotted Redshank', 'Tringa erythropus'), 
	('Common Redshank', 'Tringa totanus'), 
	('Greater Yellowlegs', 'Tringa melanoleuca'), 
	('Wilson''s Phalarope', 'Phalaropus tricolor'), 
	('Red-necked Phalarope', 'Phalaropus lobatus'), 
	('Red Phalarope', 'Phalaropus fulicarius'), 
	('Pomarine Jaeger', 'Stercorarius pomarinus'), 
	('Parasitic Jaeger', 'Stercorarius parasiticus'), 
	('Long-tailed Jaeger', 'Stercorarius longicaudus'), 
	('Dovekie', 'Alle alle'), 
	('Thick-billed Murre', 'Uria lomvia'), 
	('Ancient Murrelet', 'Synthliboramphus antiquus'), 
	('Black-legged Kittiwake', 'Rissa tridactyla'), 
	('Ivory Gull', 'Pagophila eburnea'), 
	('Sabine''s Gull', 'Xema sabini'), 
	('Bonaparte''s Gull', 'Chroicocephalus philadelphia'), 
	('Black-headed Gull', 'Chroicocephalus ridibundus'), 
	('Little Gull', 'Hydrocoloeus minutus'), 
	('Ross''s Gull', 'Rhodostethia rosea'), 
	('Laughing Gull', 'Leucophaeus atricilla'), 
	('Franklin''s Gull', 'Leucophaeus pipixcan'), 
	('Heermann''s Gull', 'Larus heermanni'), 
	('Short-billed Gull', 'Larus brachyrhynchus'), 
	('Ring-billed Gull', 'Larus delawarensis'), 
	('California Gull', 'Larus californicus'), 
	('Herring Gull', 'Larus argentatus'), 
	('Iceland Gull', 'Larus glaucoides'), 
	('Lesser Black-backed Gull', 'Larus fuscus'), 
	('Slaty-backed Gull', 'Larus schistisagus'), 
	('Glaucous-winged Gull', 'Larus glaucescens'), 
	('Glaucous Gull', 'Larus hyperboreus'), 
	('Great Black-backed Gull', 'Larus marinus'), 
	('Least Tern', 'Sternula antillarum'), 
	('Gull-billed Tern', 'Gelochelidon nilotica'), 
	('Caspian Tern', 'Hydroprogne caspia'), 
	('Black Tern', 'Chlidonias niger'), 
	('Roseate Tern', 'Sterna dougallii'), 
	('Common Tern', 'Sterna hirundo'), 
	('Arctic Tern', 'Sterna paradisaea'), 
	('Forster''s Tern', 'Sterna forsteri'), 
	('Royal Tern', 'Thalasseus maximus'), 
	('Sandwich Tern', 'Thalasseus sandvicensis'), 
	('Black Skimmer', 'Rynchops niger'), 
	('Red-throated Loon', 'Gavia stellata'), 
	('Pacific Loon', 'Gavia pacifica'), 
	('Common Loon', 'Gavia immer'), 
	('Yellow-billed Loon', 'Gavia adamsii'), 
	('Great Shearwater', 'Ardenna gravis'), 
	('Manx Shearwater', 'Puffinus puffinus'), 
	('Wood Stork', 'Mycteria americana'), 
	('Lesser Frigatebird', 'Fregata ariel'), 
	('Magnificent Frigatebird', 'Fregata magnificens'), 
	('Northern Gannet', 'Morus bassanus'), 
	('Anhinga', 'Anhinga anhinga'), 
	('Double-crested Cormorant', 'Nannopterum auritum'), 
	('Neotropic Cormorant', 'Nannopterum brasilianum'), 
	('American White Pelican', 'Pelecanus erythrorhynchos'), 
	('Brown Pelican', 'Pelecanus occidentalis'), 
	('American Bittern', 'Botaurus lentiginosus'), 
	('Least Bittern', 'Ixobrychus exilis'), 
	('Great Blue Heron', 'Ardea herodias'), 
	('Great Egret', 'Ardea alba'), 
	('Snowy Egret', 'Egretta thula'), 
	('Little Blue Heron', 'Egretta caerulea'), 
	('Tricolored Heron', 'Egretta tricolor'), 
	('Reddish Egret', 'Egretta rufescens'), 
	('Cattle Egret', 'Bubulcus ibis'), 
	('Green Heron', 'Butorides virescens'), 
	('Black-crowned Night-Heron', 'Nycticorax nycticorax'), 
	('Yellow-crowned Night-Heron', 'Nyctanassa violacea'), 
	('White Ibis', 'Eudocimus albus'), 
	('Glossy Ibis', 'Plegadis falcinellus'), 
	('White-faced Ibis', 'Plegadis chihi'), 
	('Roseate Spoonbill', 'Platalea ajaja'), 
	('Black Vulture', 'Coragyps atratus'), 
	('Turkey Vulture', 'Cathartes aura'), 
	('Osprey', 'Pandion haliaetus'), 
	('Swallow-tailed Kite', 'Elanoides forficatus'), 
	('Golden Eagle', 'Aquila chrysaetos'), 
	('Northern Harrier', 'Circus hudsonius'), 
	('Sharp-shinned Hawk', 'Accipiter striatus'), 
	('Cooper''s Hawk', 'Accipiter cooperii'), 
	('Northern Goshawk', 'Accipiter gentilis'), 
	('Bald Eagle', 'Haliaeetus leucocephalus'), 
	('Mississippi Kite', 'Ictinia mississippiensis'), 
	('Red-shouldered Hawk', 'Buteo lineatus'), 
	('Broad-winged Hawk', 'Buteo platypterus'), 
	('Short-tailed Hawk', 'Buteo brachyurus'), 
	('Swainson''s Hawk', 'Buteo swainsoni'), 
	('Red-tailed Hawk', 'Buteo jamaicensis'), 
	('Rough-legged Hawk', 'Buteo lagopus'), 
	('Ferruginous Hawk', 'Buteo regalis'), 
	('Barn Owl', 'Tyto alba'), 
	('Eastern Screech-Owl', 'Megascops asio'), 
	('Great Horned Owl', 'Bubo virginianus'), 
	('Snowy Owl', 'Bubo scandiacus'), 
	('Northern Hawk Owl', 'Surnia ulula'), 
	('Burrowing Owl', 'Athene cunicularia'), 
	('Barred Owl', 'Strix varia'), 
	('Great Gray Owl', 'Strix nebulosa'), 
	('Long-eared Owl', 'Asio otus'), 
	('Short-eared Owl', 'Asio flammeus'), 
	('Boreal Owl', 'Aegolius funereus'), 
	('Northern Saw-whet Owl', 'Aegolius acadicus'), 
	('Belted Kingfisher', 'Megaceryle alcyon'), 
	('Lewis''s Woodpecker', 'Melanerpes lewis'), 
	('Red-headed Woodpecker', 'Melanerpes erythrocephalus'), 
	('Golden-fronted Woodpecker', 'Melanerpes aurifrons'), 
	('Red-bellied Woodpecker', 'Melanerpes carolinus'), 
	('Yellow-bellied Sapsucker', 'Sphyrapicus varius'), 
	('American Three-toed Woodpecker', 'Picoides dorsalis'), 
	('Black-backed Woodpecker', 'Picoides arcticus'), 
	('Downy Woodpecker', 'Dryobates pubescens'), 
	('Red-cockaded Woodpecker', 'Dryobates borealis'), 
	('Hairy Woodpecker', 'Dryobates villosus'), 
	('Northern Flicker', 'Colaptes auratus'), 
	('Pileated Woodpecker', 'Dryocopus pileatus'), 
	('Crested Caracara', 'Caracara plancus'), 
	('American Kestrel', 'Falco sparverius'), 
	('Merlin', 'Falco columbarius'), 
	('Gyrfalcon', 'Falco rusticolus'), 
	('Peregrine Falcon', 'Falco peregrinus'), 
	('Prairie Falcon', 'Falco mexicanus'), 
	('Ash-throated Flycatcher', 'Myiarchus cinerascens'), 
	('Great Crested Flycatcher', 'Myiarchus crinitus'), 
	('Variegated Flycatcher', 'Empidonomus varius'), 
	('Tropical Kingbird', 'Tyrannus melancholicus'), 
	('Couch''s Kingbird', 'Tyrannus couchii'), 
	('Cassin''s Kingbird', 'Tyrannus vociferans'), 
	('Western Kingbird', 'Tyrannus verticalis'), 
	('Eastern Kingbird', 'Tyrannus tyrannus'), 
	('Gray Kingbird', 'Tyrannus dominicensis'), 
	('Scissor-tailed Flycatcher', 'Tyrannus forficatus'), 
	('Fork-tailed Flycatcher', 'Tyrannus savana'), 
	('Olive-sided Flycatcher', 'Contopus cooperi'), 
	('Eastern Wood-Pewee', 'Contopus virens'), 
	('Yellow-bellied Flycatcher', 'Empidonax flaviventris'), 
	('Acadian Flycatcher', 'Empidonax virescens'), 
	('Alder Flycatcher', 'Empidonax alnorum'), 
	('Willow Flycatcher', 'Empidonax traillii'), 
	('Least Flycatcher', 'Empidonax minimus'), 
	('Hammond''s Flycatcher', 'Empidonax hammondii'), 
	('Eastern Phoebe', 'Sayornis phoebe'), 
	('Say''s Phoebe', 'Sayornis saya'), 
	('Vermilion Flycatcher', 'Pyrocephalus rubinus'), 
	('Black-capped Vireo', 'Vireo atricapilla'), 
	('White-eyed Vireo', 'Vireo griseus'), 
	('Bell''s Vireo', 'Vireo bellii'), 
	('Yellow-throated Vireo', 'Vireo flavifrons'), 
	('Blue-headed Vireo', 'Vireo solitarius'), 
	('Plumbeous Vireo', 'Vireo plumbeus'), 
	('Philadelphia Vireo', 'Vireo philadelphicus'), 
	('Warbling Vireo', 'Vireo gilvus'), 
	('Red-eyed Vireo', 'Vireo olivaceus'), 
	('Loggerhead Shrike', 'Lanius ludovicianus'), 
	('Northern Shrike', 'Lanius borealis'), 
	('Canada Jay', 'Perisoreus canadensis'), 
	('Blue Jay', 'Cyanocitta cristata'), 
	('Clark''s Nutcracker', 'Nucifraga columbiana'), 
	('Black-billed Magpie', 'Pica hudsonia'), 
	('American Crow', 'Corvus brachyrhynchos'), 
	('Fish Crow', 'Corvus ossifragus'), 
	('Common Raven', 'Corvus corax'), 
	('Carolina Chickadee', 'Poecile carolinensis'), 
	('Black-capped Chickadee', 'Poecile atricapillus'), 
	('Boreal Chickadee', 'Poecile hudsonicus'), 
	('Tufted Titmouse', 'Baeolophus bicolor'), 
	('Horned Lark', 'Eremophila alpestris'), 
	('Bank Swallow', 'Riparia riparia'), 
	('Tree Swallow', 'Tachycineta bicolor'), 
	('Violet-green Swallow', 'Tachycineta thalassina'), 
	('Northern Rough-winged Swallow', 'Stelgidopteryx serripennis'), 
	('Purple Martin', 'Progne subis'), 
	('Barn Swallow', 'Hirundo rustica'), 
	('Cliff Swallow', 'Petrochelidon pyrrhonota'), 
	('Cave Swallow', 'Petrochelidon fulva'), 
	('Ruby-crowned Kinglet', 'Corthylio calendula'), 
	('Golden-crowned Kinglet', 'Regulus satrapa'), 
	('Bohemian Waxwing', 'Bombycilla garrulus'), 
	('Cedar Waxwing', 'Bombycilla cedrorum'), 
	('Red-breasted Nuthatch', 'Sitta canadensis'), 
	('White-breasted Nuthatch', 'Sitta carolinensis'), 
	('Brown Creeper', 'Certhia americana'), 
	('Blue-gray Gnatcatcher', 'Polioptila caerulea'), 
	('Rock Wren', 'Salpinctes obsoletus'), 
	('House Wren', 'Troglodytes aedon'), 
	('Winter Wren', 'Troglodytes hiemalis'), 
	('Sedge Wren', 'Cistothorus platensis'), 
	('Marsh Wren', 'Cistothorus palustris'), 
	('Carolina Wren', 'Thryothorus ludovicianus'), 
	('Bewick''s Wren', 'Thryomanes bewickii'), 
	('Gray Catbird', 'Dumetella carolinensis'), 
	('Brown Thrasher', 'Toxostoma rufum'), 
	('Sage Thrasher', 'Oreoscoptes montanus'), 
	('Northern Mockingbird', 'Mimus polyglottos'), 
	('European Starling', 'Sturnus vulgaris'), 
	('Eastern Bluebird', 'Sialia sialis'), 
	('Mountain Bluebird', 'Sialia currucoides'), 
	('Townsend''s Solitaire', 'Myadestes townsendi'), 
	('Veery', 'Catharus fuscescens'), 
	('Gray-cheeked Thrush', 'Catharus minimus'), 
	('Swainson''s Thrush', 'Catharus ustulatus'), 
	('Hermit Thrush', 'Catharus guttatus'), 
	('Wood Thrush', 'Hylocichla mustelina'), 
	('American Robin', 'Turdus migratorius'), 
	('Varied Thrush', 'Ixoreus naevius'), 
	('Northern Wheatear', 'Oenanthe oenanthe'), 
	('House Sparrow', 'Passer domesticus'), 
	('Eurasian Tree Sparrow', 'Passer montanus'), 
	('White Wagtail', 'Motacilla alba'), 
	('American Pipit', 'Anthus rubescens'), 
	('Sprague''s Pipit', 'Anthus spragueii'), 
	('Brambling', 'Fringilla montifringilla'), 
	('Evening Grosbeak', 'Coccothraustes vespertinus'), 
	('Pine Grosbeak', 'Pinicola enucleator'), 
	('Gray-crowned Rosy-Finch', 'Leucosticte tephrocotis'), 
	('House Finch', 'Haemorhous mexicanus'), 
	('Purple Finch', 'Haemorhous purpureus'), 
	('Cassin''s Finch', 'Haemorhous cassinii'), 
	('Common Redpoll', 'Acanthis flammea'), 
	('Hoary Redpoll', 'Acanthis hornemanni'), 
	('Red Crossbill', 'Loxia curvirostra'), 
	('White-winged Crossbill', 'Loxia leucoptera'), 
	('Pine Siskin', 'Spinus pinus'), 
	('American Goldfinch', 'Spinus tristis'), 
	('Lapland Longspur', 'Calcarius lapponicus'), 
	('Chestnut-collared Longspur', 'Calcarius ornatus'), 
	('Smith''s Longspur', 'Calcarius pictus'), 
	('Thick-billed Longspur', 'Rhynchophanes mccownii'), 
	('Snow Bunting', 'Plectrophenax nivalis'), 
	('Cassin''s Sparrow', 'Peucaea cassinii'), 
	('Bachman''s Sparrow', 'Peucaea aestivalis'), 
	('Grasshopper Sparrow', 'Ammodramus savannarum'), 
	('Black-throated Sparrow', 'Amphispiza bilineata'), 
	('Lark Sparrow', 'Chondestes grammacus'), 
	('Lark Bunting', 'Calamospiza melanocorys'), 
	('Chipping Sparrow', 'Spizella passerina'), 
	('Clay-colored Sparrow', 'Spizella pallida'), 
	('Field Sparrow', 'Spizella pusilla'), 
	('Brewer''s Sparrow', 'Spizella breweri'), 
	('Fox Sparrow', 'Passerella iliaca'), 
	('American Tree Sparrow', 'Spizelloides arborea'), 
	('Dark-eyed Junco', 'Junco hyemalis'), 
	('White-crowned Sparrow', 'Zonotrichia leucophrys'), 
	('Golden-crowned Sparrow', 'Zonotrichia atricapilla'), 
	('Harris''s Sparrow', 'Zonotrichia querula'), 
	('White-throated Sparrow', 'Zonotrichia albicollis'), 
	('Sagebrush Sparrow', 'Artemisiospiza nevadensis'), 
	('Vesper Sparrow', 'Pooecetes gramineus'), 
	('LeConte''s Sparrow', 'Ammospiza leconteii'), 
	('Nelson''s Sparrow', 'Ammospiza nelsoni'), 
	('Henslow''s Sparrow', 'Centronyx henslowii'), 
	('Savannah Sparrow', 'Passerculus sandwichensis'), 
	('Song Sparrow', 'Melospiza melodia'), 
	('Lincoln''s Sparrow', 'Melospiza lincolnii'), 
	('Swamp Sparrow', 'Melospiza georgiana'), 
	('Green-tailed Towhee', 'Pipilo chlorurus'), 
	('Spotted Towhee', 'Pipilo maculatus'), 
	('Eastern Towhee', 'Pipilo erythrophthalmus'), 
	('Yellow-breasted Chat', 'Icteria virens'), 
	('Yellow-headed Blackbird', 'Xanthocephalus xanthocephalus'), 
	('Bobolink', 'Dolichonyx oryzivorus'), 
	('Eastern Meadowlark', 'Sturnella magna'), 
	('Western Meadowlark', 'Sturnella neglecta'), 
	('Orchard Oriole', 'Icterus spurius'), 
	('Hooded Oriole', 'Icterus cucullatus'), 
	('Bullock''s Oriole', 'Icterus bullockii'), 
	('Baltimore Oriole', 'Icterus galbula'), 
	('Red-winged Blackbird', 'Agelaius phoeniceus'), 
	('Shiny Cowbird', 'Molothrus bonariensis'), 
	('Brown-headed Cowbird', 'Molothrus ater'), 
	('Rusty Blackbird', 'Euphagus carolinus'), 
	('Brewer''s Blackbird', 'Euphagus cyanocephalus'), 
	('Common Grackle', 'Quiscalus quiscula'), 
	('Boat-tailed/Great-tailed Grackle', 'Quiscalus major/mexicanus'), 
	('Ovenbird', 'Seiurus aurocapilla'), 
	('Worm-eating Warbler', 'Helmitheros vermivorum'), 
	('Louisiana Waterthrush', 'Parkesia motacilla'), 
	('Northern Waterthrush', 'Parkesia noveboracensis'), 
	('Golden-winged Warbler', 'Vermivora chrysoptera'), 
	('Blue-winged Warbler', 'Vermivora cyanoptera'), 
	('Black-and-white Warbler', 'Mniotilta varia'), 
	('Prothonotary Warbler', 'Protonotaria citrea'), 
	('Swainson''s Warbler', 'Limnothlypis swainsonii'), 
	('Tennessee Warbler', 'Leiothlypis peregrina'), 
	('Orange-crowned Warbler', 'Leiothlypis celata'), 
	('Lucy''s Warbler', 'Leiothlypis luciae'), 
	('Nashville Warbler', 'Leiothlypis ruficapilla'), 
	('Virginia''s Warbler', 'Leiothlypis virginiae'), 
	('Connecticut Warbler', 'Oporornis agilis'), 
	('Mourning Warbler', 'Geothlypis philadelphia'), 
	('Kentucky Warbler', 'Geothlypis formosa'), 
	('Common Yellowthroat', 'Geothlypis trichas'), 
	('Hooded Warbler', 'Setophaga citrina'), 
	('American Redstart', 'Setophaga ruticilla'), 
	('Kirtland''s Warbler', 'Setophaga kirtlandii'), 
	('Cape May Warbler', 'Setophaga tigrina'), 
	('Cerulean Warbler', 'Setophaga cerulea'), 
	('Northern Parula', 'Setophaga americana'), 
	('Magnolia Warbler', 'Setophaga magnolia'), 
	('Bay-breasted Warbler', 'Setophaga castanea'), 
	('Blackburnian Warbler', 'Setophaga fusca'), 
	('Yellow Warbler', 'Setophaga petechia'), 
	('Chestnut-sided Warbler', 'Setophaga pensylvanica'), 
	('Blackpoll Warbler', 'Setophaga striata'), 
	('Black-throated Blue Warbler', 'Setophaga caerulescens'), 
	('Palm Warbler', 'Setophaga palmarum'), 
	('Pine Warbler', 'Setophaga pinus'), 
	('Yellow-rumped Warbler', 'Setophaga coronata'), 
	('Yellow-throated Warbler', 'Setophaga dominica'), 
	('Prairie Warbler', 'Setophaga discolor'), 
	('Black-throated Gray Warbler', 'Setophaga nigrescens'), 
	('Townsend''s Warbler', 'Setophaga townsendi'), 
	('Black-throated Green Warbler', 'Setophaga virens'), 
	('Canada Warbler', 'Cardellina canadensis'), 
	('Wilson''s Warbler', 'Cardellina pusilla'), 
	('Painted Redstart', 'Myioborus pictus'), 
	('Hepatic Tanager', 'Piranga flava'), 
	('Summer Tanager', 'Piranga rubra'), 
	('Scarlet Tanager', 'Piranga olivacea'), 
	('Western Tanager', 'Piranga ludoviciana'), 
	('Northern Cardinal', 'Cardinalis cardinalis'), 
	('Rose-breasted Grosbeak', 'Pheucticus ludovicianus'), 
	('Black-headed Grosbeak', 'Pheucticus melanocephalus'), 
	('Blue Grosbeak', 'Passerina caerulea'), 
	('Lazuli Bunting', 'Passerina amoena'), 
	('Indigo Bunting', 'Passerina cyanea'), 
	('Painted Bunting', 'Passerina ciris'), 
	('Dickcissel', 'Spiza americana');
